version: 1
accounts:
  - name: "client-1"
    coins: ["500token", "100000000stake"]
    mnemonic: "drastic away just dash boy hunt theory just hockey twice bread circle demand educate taste between try keen enjoy assist uncover believe inspire discover"
  - name: "client-2"
    coins: ["500token"]
    mnemonic: "again pull purity deposit parent craft electric degree load weekend satisfy easily dizzy trick unveil town cram opinion bonus shoe combine deliver zero cradle"
validators:
  - name: client-1
    bonded: "100000000stake"
    home: "./docker/validator"
    config:
      moniker: "lottery"
      timeout_commit: "5m"
    client:
      chain-id: "lottery-1"
      keyring-backend: "test"
build:
  binary: "lotteryd"
  main: "./cmd/lotteryd"
genesis:
  chain_id: "lottery-1"
client:
  typescript:
    path: "ts-client"
