version: "3.8"

networks:
  net-private:
  net-public:

services:
  kms:
    command: start --config /root/tmkms/tmkms.toml
    container_name: kms
    image: tmkms_i:v0.12.2
    networks:
      - net-private
    volumes:
      - ./docker/kms:/root/tmkms

  validator:
    command: start
    container_name: validator
    image: lotteryd_i
    networks:
      - net-private
    volumes:
      - ./docker/validator:/root/.loterry
    depends_on:
      - kms

  sentry:
    command: start
    container_name: sentry
    image: lotteryd_i
    networks:
      - net-private
      - net-public
    volumes:
      - ./docker/sentry:/root/.loterry

  node:
    command: start
    container_name: node
    image: lotteryd_i
    networks:
      - net-public
    volumes:
      - ./docker/node:/root/.loterry
    ports:
      - 0.0.0.0:26657:26657
