name: golang-security-action

on: 
  push: 
    branches:
          - main
  pull_request:

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ynniss/golang-security-action@master
